In [1]:
import sqlalchemy
import pymysql
from sqlalchemy.schema import CreateSchema
from sqlalchemy import create_engine

In [2]:
#for connecting to mysql
pymysql.install_as_MySQLdb()

In [31]:
#create 3 schemas 
# indices  = ['Nifty50', 'RTSI', 'Bovespa']
indices  = ['Nifty50', 'RTSI']

In [4]:
# Define a function to create these above mentioned schemas, use this for a single schema creation
# def schemacreator(index):
#     engine = sqlalchemy.create_engine('mysql://root:Shrikanth_1@localhost:3306/')
#     engine.execute(sqlalchemy.schema.CreateSchema(index))
#     engine

In [5]:
def schemacreator(index):
    engine = sqlalchemy.create_engine('mysql://root:Shrikanth_1@localhost:3306/')
    with engine.connect() as connection:
        connection.execute(CreateSchema(index, if_not_exists=True))
        connection.commit()

In [6]:
#Call the function to create the schemas
for index in indices:
    schemacreator(index)

In [7]:
import pandas as pd

In [17]:

nifty = pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')[2]
rts = pd.read_html('https://en.wikipedia.org/wiki/RTS_Index')[1]
# bovespa = pd.read_html('https://en.wikipedia.org/wiki/List_of_companies_listed_on_B3')[0]

In [10]:
nifty

                       Company Name      Symbol              Sector[16]
0                 Adani Enterprises    ADANIENT             Diversified
1                 Adani Ports & SEZ  ADANIPORTS          Infrastructure
2                  Apollo Hospitals  APOLLOHOSP              Healthcare
3                      Asian Paints  ASIANPAINT       Consumer Durables
4                         Axis Bank    AXISBANK                 Banking
5                        Bajaj Auto  BAJAJ-AUTO              Automobile
6                     Bajaj Finance  BAJFINANCE      Financial Services
7                     Bajaj Finserv  BAJAJFINSV      Financial Services
8                  Bharat Petroleum        BPCL      Energy - Oil & Gas
9                     Bharti Airtel  BHARTIARTL       Telecommunication
10             Britannia Industries   BRITANNIA          Consumer Goods
11                            Cipla       CIPLA         Pharmaceuticals
12                       Coal India   COALINDIA           Energy - Coal
13              Divi's Laboratories    DIVISLAB         Pharmaceuticals
14         Dr. Reddy's Laboratories     DRREDDY         Pharmaceuticals
15                    Eicher Motors   EICHERMOT              Automobile
16                Grasim Industries      GRASIM               Materials
17                          HCLTech     HCLTECH  Information Technology
18                        HDFC Bank    HDFCBANK                 Banking
19                        HDFC Life    HDFCLIFE      Financial Services
20                    Hero MotoCorp  HEROMOTOCO              Automobile
21              Hindalco Industries    HINDALCO                  Metals
22               Hindustan Unilever  HINDUNILVR          Consumer Goods
23                       ICICI Bank   ICICIBANK                 Banking
24                    IndusInd Bank  INDUSINDBK                 Banking
25                          Infosys        INFY  Information Technology
26                              ITC         ITC          Consumer Goods
27                        JSW Steel    JSWSTEEL                  Metals
28              Kotak Mahindra Bank   KOTAKBANK                 Banking
29                  Larsen & Toubro          LT            Construction
30                      LTIMindtree        LTIM  Information Technology
31              Mahindra & Mahindra         M&M              Automobile
32                    Maruti Suzuki      MARUTI              Automobile
33                     Nestl√© India   NESTLEIND          Consumer Goods
34                             NTPC        NTPC          Energy - Power
35  Oil and Natural Gas Corporation        ONGC      Energy - Oil & Gas
36                       Power Grid   POWERGRID          Energy - Power
37              Reliance Industries    RELIANCE             Diversified
38       SBI Life Insurance Company     SBILIFE      Financial Services
39              State Bank of India        SBIN                 Banking
40                       Sun Pharma   SUNPHARMA         Pharmaceuticals
41                      Tata Motors  TATAMOTORS              Automobile
42                       Tata Steel   TATASTEEL                  Metals
43        Tata Consultancy Services         TCS  Information Technology
44           Tata Consumer Products  TATACONSUM          Consumer Goods
45                    Tech Mahindra       TECHM  Information Technology
46                    Titan Company       TITAN       Consumer Durables
47                 UltraTech Cement  ULTRACEMCO               Materials
48                              UPL         UPL               Chemicals
49                            Wipro       WIPRO  Information Technology

In [11]:
nifty = nifty.Symbol.to_list()
nifty

['ADANIENT',
 'ADANIPORTS',
 'APOLLOHOSP',
 'ASIANPAINT',
 'AXISBANK',
 'BAJAJ-AUTO',
 'BAJFINANCE',
 'BAJAJFINSV',
 'BPCL',
 'BHARTIARTL',
 'BRITANNIA',
 'CIPLA',
 'COALINDIA',
 'DIVISLAB',
 'DRREDDY',
 'EICHERMOT',
 'GRASIM',
 'HCLTECH',
 'HDFCBANK',
 'HDFCLIFE',
 'HEROMOTOCO',
 'HINDALCO',
 'HINDUNILVR',
 'ICICIBANK',
 'INDUSINDBK',
 'INFY',
 'ITC',
 'JSWSTEEL',
 'KOTAKBANK',
 'LT',
 'LTIM',
 'M&M',
 'MARUTI',
 'NESTLEIND',
 'NTPC',
 'ONGC',
 'POWERGRID',
 'RELIANCE',
 'SBILIFE',
 'SBIN',
 'SUNPHARMA',
 'TATAMOTORS',
 'TATASTEEL',
 'TCS',
 'TATACONSUM',
 'TECHM',
 'TITAN',
 'ULTRACEMCO',
 'UPL',
 'WIPRO']

In [12]:
rts

,Company,Ticker symbol,Stock type,Industry
0,AFK Sistema,AFKS,Common,Conglomerate
1,Aeroflot,AFLT,Common,Transportation
2,Rusagro,AGRO,Depositary receipt,Agriculture
3,Acron,AKRN,Common,Chemicals
4,Lenta,LNTA,Depositary receipt,Retail
5,Credit Bank of Moscow,CBOM,Common,Banking
6,Detsky Mir,DSKY,Common,Retail
7,SeverStal,CHMF,Common,Mining & Metallurgy
8,DIXY,DIXY,Common,Retail
9,FGC UES,FEES,Common,Electric utility
10,Gazprom,GAZP,Common,Oil & gas
11,Norilsk Nickel,GMKN,Common,Mining & Metallurgy
12,RusHydro,HYDR,Common,Energy
13,Inter RAO,IRAO,Common,Energy
14,Lukoil,LKOH,Common,Oil & gas
15,LSR Group,LSRG,Common,Real estate development
16,Magnitogorsk Iron and Steel Works,MAGN,Common,Metallurgy
17,MegaFon,MFON,Common,Telecommunication
18,OJSC Magnit,MGNT,Common,Retail
19,Moscow Exchange,MOEX,Common,Stock exchange
20,Mosenergo,MSNG,Common,Energy
21,Mechel,MTLR,Common,Mining & Metallurgy
22,Alrosa,ALRS,Common,Mining
23,Mobile TeleSystems,MTSS,Common,Telecommunication
24,M.video,MVID,Common,Retail
25,Novolipetsk Steel,NLMK,Common,Metallurgy
26,Novorossiysk Commercial Sea Port,NMPT,Common,Transportation
27,Novatek,NVTK,Common,Oil & gas
28,PhosAgro,PHOR,Common,Chemicals
29,PIK Group,PIKK,Common,Real estate development
30,Polyus Gold,PLZL,Common,Mining
31,Polymetal International,POLY,Common,Mining
32,Rosneft,ROSN,Common,Oil & gas
33,Rosseti,RSTI,Common,Electric utility
34,Rostelecom,RTKM,Common,Telecommunication
35,Rusal,RUALR,Russian depositary receipt (RDR),Mining
36,SFI,EPLN,Common,Leasing
37,Sberbank,SBER,Common,Banking
38,Sberbank,SBERP,Preferred,Banking
39,Surgutneftegas,SNGS,Common,Oil & gas
40,Surgutneftegas,SNGSP,Preferred,Oil & gas
41,Tatneft,TATN,Common,Oil & gas
42,Tatneft,TATNP,Preferred,Oil & gas
43,OAO TMK,TRMK,Common,Steel industry
44,Transneft,TRNFP,Preferred,Oil & gas
45,Unipro,UPRO,Common,Electric utility
46,Russneft,RNFT,Common,Refining
47,United Wagon Company,UWGN,Common,Mechanical engineering
48,VTB Bank,VTBR,Common,Banking
49,Yandex,YNDX,Common,Internet

In [13]:
rts = rts['Ticker symbol'].to_list()
rts

['AFKS',
 'AFLT',
 'AGRO',
 'AKRN',
 'LNTA',
 'CBOM',
 'DSKY',
 'CHMF',
 'DIXY',
 'FEES',
 'GAZP',
 'GMKN',
 'HYDR',
 'IRAO',
 'LKOH',
 'LSRG',
 'MAGN',
 'MFON',
 'MGNT',
 'MOEX',
 'MSNG',
 'MTLR',
 'ALRS',
 'MTSS',
 'MVID',
 'NLMK',
 'NMPT',
 'NVTK',
 'PHOR',
 'PIKK',
 'PLZL',
 'POLY',
 'ROSN',
 'RSTI',
 'RTKM',
 'RUALR',
 'EPLN',
 'SBER',
 'SBERP',
 'SNGS',
 'SNGSP',
 'TATN',
 'TATNP',
 'TRMK',
 'TRNFP',
 'UPRO',
 'RNFT',
 'UWGN',
 'VTBR',
 'YNDX']

In [19]:
# bovespa

In [20]:
# bovespa = bovespa.Ticker.to_list()
# bovespa

In [21]:
# string comprehension
nifty = [i+'.NS' for i in nifty]
rts = [i+'.ME' for i in rts]
# bovespa = [i+'.SA' for i in bovespa]

In [27]:
nifty[0]
rts[0]
# bovespa[0]

'Company.ME'

In [26]:
import yfinance as yf

In [32]:
yf.download(nifty[0], start='2023-05-20')

[*********************100%%**********************]  2 of 2 completed

2 Failed downloads:
['NAME.NS', 'COMPANY']: Exception('%ticker%: No timezone found, symbol may be delisted')

Empty DataFrame
Columns: [(Adj Close, COMPANY), (Adj Close, NAME.NS), (Close, COMPANY), (Close, NAME.NS), (High, COMPANY), (High, NAME.NS), (Low, COMPANY), (Low, NAME.NS), (Open, COMPANY), (Open, NAME.NS), (Volume, COMPANY), (Volume, NAME.NS)]
Index: []

In [29]:
#Create a dictonary called mapper
# mapper = {'Nifty50': nifty, 'Bovespa': bovespa, 'RTSI': rts}
mapper = {'Nifty50': nifty, 'RTSI': rts}

In [ ]:
for symbol in mapper['Nifty50']:
    print(symbol)

ADANIENT.NS
ADANIPORTS.NS
APOLLOHOSP.NS
ASIANPAINT.NS
AXISBANK.NS
BAJAJ-AUTO.NS
BAJFINANCE.NS
BAJAJFINSV.NS
BPCL.NS
BHARTIARTL.NS
BRITANNIA.NS
CIPLA.NS
COALINDIA.NS
DIVISLAB.NS
DRREDDY.NS
EICHERMOT.NS
GRASIM.NS
HCLTECH.NS
HDFCBANK.NS
HDFCLIFE.NS
HEROMOTOCO.NS
HINDALCO.NS
HINDUNILVR.NS
ICICIBANK.NS
INDUSINDBK.NS
INFY.NS
ITC.NS
JSWSTEEL.NS
KOTAKBANK.NS
LT.NS
LTIM.NS
M&M.NS
MARUTI.NS
NESTLEIND.NS
NTPC.NS
ONGC.NS
POWERGRID.NS
RELIANCE.NS
SBILIFE.NS
SBIN.NS
SUNPHARMA.NS
TATAMOTORS.NS
TATASTEEL.NS
TCS.NS
TATACONSUM.NS
TECHM.NS
TITAN.NS
ULTRACEMCO.NS
UPL.NS
WIPRO.NS

In [33]:
# Get the prices of each stock and load into mysql
for index in indices:
    engine = sqlalchemy.create_engine('mysql://root:Shrikanth_1@localhost:3306/'+index) # select the correct schema respectively
    for symbol in mapper[index]:
        df = yf.download(symbol, start = '2023-01-01')
        df = df.reset_index() # reset the index so datetime will be column and not index
        df.to_sql(symbol, engine)

[*********************100%%**********************]  1 of 2 completed

2 Failed downloads:
['NAME.NS', 'COMPANY']: Exception('%ticker%: No timezone found, symbol may be delisted')

ValueError: Table 'Company Name.NS' already exists.